# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: http://localhost:3000/
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: 1f80b7b3eabea2089220a1b238f63dc90d643784bd56e181fdaee98e32a6f377d5948c4cbe809f0a61a5093aac796bb42eb3bf1b6b0ff1fe12329c19af98841f

test:
  secret_key_base: 16993373e0b2bdb8b932ee65e02a7f33daa563568a01526e42a1fd1f2e143b0cd8c4ec2cc77aead0f35517a33fa4a5856cc62a6926e855aca71fad3f41416c6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
